//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUIforSMDV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SciezkaDoSMDV {
            get {
                return ((string)(this["SciezkaDoSMDV"]));
            }
            set {
                this["SciezkaDoSMDV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SciezkaDoPySMDV {
            get {
                return ((string)(this["SciezkaDoPySMDV"]));
            }
            set {
                this["SciezkaDoPySMDV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Macierze\\\\")]
        public string SciezkaDoMacierzy {
            get {
                return ((string)(this["SciezkaDoMacierzy"]));
            }
            set {
                this["SciezkaDoMacierzy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logi\\\\")]
        public string SciezkaDoLogow {
            get {
                return ((string)(this["SciezkaDoLogow"]));
            }
            set {
                this["SciezkaDoLogow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string Separator {
            get {
                return ((string)(this["Separator"]));
            }
            set {
                this["Separator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b/d")]
        public string SymbolBrakDanych {
            get {
                return ((string)(this["SymbolBrakDanych"]));
            }
            set {
                this["SymbolBrakDanych"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public string Powtorzenia {
            get {
                return ((string)(this["Powtorzenia"]));
            }
            set {
                this["Powtorzenia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool KomunikatyNaKonsoli {
            get {
                return ((bool)(this["KomunikatyNaKonsoli"]));
            }
            set {
                this["KomunikatyNaKonsoli"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UtworzenieLogu {
            get {
                return ((bool)(this["UtworzenieLogu"]));
            }
            set {
                this["UtworzenieLogu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObliczeniaNaCPU {
            get {
                return ((bool)(this["ObliczeniaNaCPU"]));
            }
            set {
                this["ObliczeniaNaCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObliczeniaNaCUDA {
            get {
                return ((bool)(this["ObliczeniaNaCUDA"]));
            }
            set {
                this["ObliczeniaNaCUDA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Macierze {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Macierze"]));
            }
            set {
                this["Macierze"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObliczeniaSMDV {
            get {
                return ((bool)(this["ObliczeniaSMDV"]));
            }
            set {
                this["ObliczeniaSMDV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObliczeniaPySMDV {
            get {
                return ((bool)(this["ObliczeniaPySMDV"]));
            }
            set {
                this["ObliczeniaPySMDV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PythonExe {
            get {
                return ((string)(this["PythonExe"]));
            }
            set {
                this["PythonExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RozmiarBloku {
            get {
                return ((string)(this["RozmiarBloku"]));
            }
            set {
                this["RozmiarBloku"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string SliceSize {
            get {
                return ((string)(this["SliceSize"]));
            }
            set {
                this["SliceSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string WatkiNaWiersz {
            get {
                return ((string)(this["WatkiNaWiersz"]));
            }
            set {
                this["WatkiNaWiersz"] = value;
            }
        }
    }
}
